Added implementations to 10 UDTs
MiHo2757/PFMCPP_Project3 pull request #2
Opened 2023-11-05 13:16 UTC by MiHo2757

Slack ID: MiHo2757

2023-11-05 21:21 UTC, matkatmusic requested changes

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +    void run(int howFast, bool startWithLeftFoot);
You need to include the implementation of the run function.
You need to follow the directions as well regarding what to do for the left foot and right foot structure.
- [ ] revise

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +    std::cout << "You are online." << std::endl;
- [ ] revise: Indentation

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +}
If you find yourself writing code like this:
```
int Type::someFunction()
{
    if( someExpression )
    {
        someStatement();
        return aValue;
    } 
    else 
    {
        return anotherValue;
    }
}
```
You do not need the `else` block.  Here's why:
`return` statements are the last thing that **ever happens** in a function.
When the `if()` expression is evaluated as `true` and the block is entered, the `return aValue;` is the last line of code to be executed before the function exits.
but when the `if()` expression evaluates as `false` and the block is **NOT** entered, the next thing that happens is `return anotherValue;`
you have no code after the `else` block that needs executing, since your `else` block contains a `return` statement.
that means you do **NOT** need the `else` block, and it is just causing visual clutter.
```
int Type::someFunction()
{
    if( someExpression )
    {
        someStatement();
        return aValue;
    } 
    
    return anotherValue;
}
```
- [ ] revise

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +}
- [ ] revise

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +}
- [ ] revise

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +}
- [ ] revise: indentation

2023-11-05 21:21 UTC, matkatmusic commented on main.cpp
> +}
- [ ] revise

2023-11-06 00:12 UTC, MiHo2757 commented on main.cpp
> +    void run(int howFast, bool startWithLeftFoot);
I have managed to add an implementation of the run function and the stepSize part seems fine but I've got myself into a mess with the stepForward part. Please advise.

2023-11-06 23:54 UTC, matkatmusic requested changes
Still not correct.  Please review our Slack discussion and update accordingly.

2023-11-06 23:54 UTC, matkatmusic commented on main.cpp
> +   distanceTravelled += leftFoot.stepSize + rightFoot.stepSize;
`stepSize` is a function, not a variable
Copy the code EXACTLY as shown in the video. 
Then make your `Foot` structure work correctly without errors and WITHOUT modifying this `run` function
- [ ] revise

2023-11-07 00:49 UTC, MiHo2757 commented
New commit added

2023-11-07 18:57 UTC, matkatmusic approved these changes

2023-11-07 18:57 UTC, merged